#!/usr/bin/env bash

bundle install
git submodule init
git submodule update
bundle exec rake db:drop db:create db:migrate db:seed
cd public/
git checkout master
npm install -g grunt
npm install grunt-ember-templates
grunt
cd ../

